apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test4
  namespace: default
  description: "test4"
  annotations:
    github.com/project-slug: le01lopez/test4
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: "group:default/guests"
  providesApis: 
    - "api:default/products-api"
