apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: product-api
  description: API para la gestión de productos
  owner: "group:default/guests"
spec:
  type: openapi
  lifecycle: experimental
  definition:
    $text: |
      openapi: 3.0.0
      info:
        title: ProjectName API
        description: Una API web ASP.NET Core para administrar clientes
        version: v1
      servers:
        - url: https://localhost:8081
      paths:
        /api/products/{id}:
          get:
            tags:
              - Products
            operationId: Products_GetProduct
            parameters:
              - name: id
                in: path
                required: true
                schema:
                  type: string
                  format: guid
                x-position: 1
            responses:
              '200':
                description: ''
                content:
                  application/octet-stream:
                    schema:
                      type: string
                      format: binary
          put:
            tags:
              - Products
            operationId: Products_UpdateProduct
            parameters:
              - name: id
                in: path
                required: true
                schema:
                  type: string
                  format: guid
                x-position: 1
            requestBody:
              x-name: request
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/UpdateProductRequest'
              required: true
              x-position: 2
            responses:
              '200':
                description: ''
                content:
                  application/octet-stream:
                    schema:
                      type: string
                      format: binary
          delete:
            tags:
              - Products
            operationId: Products_DeleteProduct
            parameters:
              - name: id
                in: path
                required: true
                schema:
                  type: string
                  format: guid
                x-position: 1
            responses:
              '200':
                description: ''
                content:
                  application/octet-stream:
                    schema:
                      type: string
                      format: binary
        /api/products:
          get:
            tags:
              - Products
            operationId: Products_GetProducts
            responses:
              '200':
                description: ''
                content:
                  application/octet-stream:
                    schema:
                      type: string
                      format: binary
          post:
            tags:
              - Products
            operationId: Products_CreateProduct
            requestBody:
              x-name: request
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/CreateProductRequest'
              required: true
              x-position: 1
            responses:
              '200':
                description: ''
                content:
                  application/octet-stream:
                    schema:
                      type: string
                      format: binary
      components:
        schemas:
          CreateProductRequest:
            type: object
            additionalProperties: false
            properties:
              name:
                type: string
              description:
                type: string
          UpdateProductRequest:
            type: object
            additionalProperties: false
            properties:
              name:
                type: string
              description:
                type: string
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test4"
  description: "test4"
  annotations:
    github.com/project-slug: le01lopez/test4
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/guests"
  providesApis: 
    - "api:default/product-api" 
  consumesApis: []
