apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test4"
  description: "test4"
  annotations:
    github.com/project-slug: le01lopez/test4
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/guests"